services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: digitalclass-backend
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - .env.backend
    networks:
      - digitalclass-network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    container_name: digitalclass-frontend
    restart: always
    ports:
      - "8004:3000" # Mapeia a porta interna 3000 do Next para a 8004 da VPS
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - digitalclass-network

networks:
  digitalclass-network:
    driver: bridge