services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY:-digitalclass}/backend:latest
    container_name: digitalclass-backend
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - .env.backend # O Docker vai ler as chaves daqui
    networks:
      - digitalclass-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY:-digitalclass}/frontend:latest
    container_name: digitalclass-frontend
    restart: always
    ports:
      - "8004:8004"
    env_file:
      - .env.frontend # O Docker vai ler as chaves daqui
    depends_on:
      - backend
    networks:
      - digitalclass-network

networks:
  digitalclass-network:
    driver: bridge
